name: freecad-rt-deps-core22
base: core22
adopt-info: occt
summary: Dependencies for freecad-realthunder snaps
description: |
  - OCCT
  - GMSH
grade: stable
confinement: strict

parts:
  occt:
    plugin: cmake
    source-type: local
    source: "${CRAFT_PROJECT_DIR}"
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DUSE_TBB:BOOL=off
      - -DUSE_VTK:BOOL=off
      - -DUSE_FREEIMAGE:BOOL=on
      - -DBUILD_RELEASE_DISABLE_EXCEPTIONS:BOOL=off
      - -DUSE_RAPIDJSON:BOOL=on
      - -DCMAKE_BUILD_TYPE=Release
    build-packages:
      - libfreeimage-dev
      - libfreetype6-dev
      - tcl-dev
      - tk-dev
      - libgl-dev
      - rapidjson-dev
    build-environment:
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/"
    override-build: |
      craftctl default
      find "${CRAFT_PART_INSTALL}/usr/lib/cmake" \
        -type f \
        -name "*.cmake" \
        -exec sed -i -e 's|\\${OCCT_INSTALL_BIN_LETTER}||g' {} \;
      cd "${CRAFT_PROJECT_DIR}"
      iso_date=$(date -I)
      git_hash=$(git rev-parse --short=8 HEAD)
      version="$iso_date-g$git_hash"
      craftctl set version="$version"
    prime:
      -  -usr/share/opencascade

  gmsh: # FEM
    after: [occt]
    plugin: cmake
    source: https://gitlab.onelab.info/gmsh/gmsh.git
    source-tag: gmsh_4_11_1
    build-packages:
      - tk-dev
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_PREFIX_PATH=${CRAFT_STAGE}/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DENABLE_BUILD_DYNAMIC=1
      - -DENABLE_MED=0
      - -DENABLE_FLTK=0
    build-environment:
      - LD_LIBRARY_PATH: "$CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET:$CRAFT_STAGE/usr/lib"
  
  cleanup:
    after: [occt, gmsh]
    plugin: nil
    override-prime: |
      set -eux
      for cruft in bug lintian man; do
        rm -rf $CRAFT_PRIME/usr/share/$cruft
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
      find $CRAFT_PRIME/usr/share -type d -empty -delete
